//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2022. 04. 15. 16:47:26
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace enMetalBands
{
    public enum Genres : int
    {
        alternative_metal,
        avantgarde_metal,
        black_metal,
        death_metal,
        djent,
        doom_metal,
        folk_metal,
        gothic_metal,
        hardcore,
        heavy_metal,
        industrial_metal,
        metalgaze,
        post_metal,
        power_metal,
        progressive_metal,
        sludge_metal,
        symphonic_metal,
        thrash_metal
    }
}
