//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2022. 04. 15. 23:40:00
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace enMetalBands
{
    public partial class enMetalBand {

        public enMetalBand()
        {
            this.enBandMembers = new List<enBandMembers>();
            this.enAlbums = new List<enAlbum>();
            OnCreated();
        }

        public virtual int Band_id { get; set; }

        public virtual string Band_name { get; set; }

        public virtual int Date_founding { get; set; }

        public virtual Genres Genre_name { get; set; }

        public virtual IList<enBandMembers> enBandMembers { get; set; }

        public virtual IList<enAlbum> enAlbums { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
